In [1]:
import torch

In [3]:
x = torch.tensor([1.0, 2, 3], requires_grad=True)
y = x.detach()

print(x)
print(y)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])


In [4]:
print(id(x))
print(id(y))

2520291324096
2520145905936


In [5]:
print(x.storage().data_ptr())
print(y.storage().data_ptr())

3739582732352
3739582732352


C:\Users\Beanmeat\AppData\Local\Temp\ipykernel_13340\515868380.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(x.storage().data_ptr())


In [6]:
z1 = x ** 2
print(z1)

z2 = y ** 2
print(z2)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([1., 4., 9.])


In [8]:
print(z1.requires_grad)
z1.sum().backward()

True


In [9]:
print(z2.requires_grad)
z2.sum().backward()

False


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn