In [8]:
import torch
import torch.nn as nn

In [9]:
# 输入
x = torch.randn(3,2)
print(x)

tensor([[-0.0429,  0.7549],
        [-0.9896, -0.9299],
        [ 0.4629,  1.6170]])


In [10]:
# 真实值（标签）
t = torch.tensor([[0,1],[1,0],[0,1]],dtype=torch.float)
print(t)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [11]:
# 预测值（输出）
y = torch.sigmoid(x)
print(y)

tensor([[0.4893, 0.6802],
        [0.2710, 0.2829],
        [0.6137, 0.8344]])


In [12]:
# 定义损失函数，计算损失值
loss = nn.BCELoss()
print(loss(y,t))

tensor(0.6380)
