In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 真实值为类别类型,一共六条数据，每条数据8个分类（0~7）
x = torch.randn(6,8)
print(x)

tensor([[-0.2969, -1.5593, -0.7408, -0.2158,  0.0681, -0.2698, -0.3369,  1.4494],
        [-0.4811, -0.1295, -0.4625, -0.7095,  0.2045,  1.3918,  0.5984,  1.5083],
        [ 0.2670,  0.0413,  0.2821, -0.1075,  1.6535, -1.2691,  1.5143,  2.4760],
        [ 0.4698,  0.9527,  0.7668,  1.2643, -1.6340,  1.0746, -0.0560, -1.8893],
        [-0.1812,  0.1016,  0.5255, -0.2239, -0.9747, -0.4033,  0.9836,  0.1707],
        [-0.5810,  0.0580,  0.3233, -0.8555,  1.5702, -0.5210,  0.5505,  0.0118]])


In [3]:
t = torch.tensor([1,0,3,2,5,7])
print(t)

tensor([1, 0, 3, 2, 5, 7])


In [4]:
# 计算损失
loss = nn.CrossEntropyLoss()
print(loss(x,t))

tensor(2.8726)


In [5]:
# 真实值为分类概率或独热编码
t = torch.randn(6,8).softmax(dim=1)
print(t)

tensor([[0.0450, 0.1932, 0.1849, 0.2418, 0.1995, 0.0392, 0.0277, 0.0687],
        [0.0067, 0.0643, 0.2722, 0.0570, 0.0036, 0.3340, 0.2385, 0.0236],
        [0.0089, 0.0794, 0.0409, 0.0381, 0.1614, 0.3996, 0.0051, 0.2667],
        [0.1329, 0.1070, 0.0387, 0.0827, 0.1081, 0.2152, 0.0842, 0.2311],
        [0.1714, 0.0838, 0.0442, 0.0305, 0.2712, 0.3057, 0.0333, 0.0600],
        [0.0976, 0.0648, 0.0273, 0.0994, 0.0393, 0.5562, 0.0361, 0.0792]])


In [6]:
# 计算损失
loss = nn.CrossEntropyLoss()
print(loss(x,t))

tensor(2.6236)


In [7]:
input = torch.randn(6,8)
print(input)
target = torch.randint(low = 0, high = 8, size = (6,))
print(target)

tensor([[-1.1361, -0.4171, -0.4415,  0.4455, -0.2229,  1.6560,  1.8630,  0.3770],
        [ 1.3298,  1.3770,  0.9086,  0.5778, -1.4939, -0.6726,  0.0165, -1.9371],
        [-0.2835, -0.3447, -1.4530,  0.4311,  0.3033, -1.3525, -2.8027,  1.0679],
        [ 1.3219,  0.8015,  1.3141,  0.0476, -0.5489,  1.9251, -1.3180,  1.0639],
        [ 0.4006,  1.6761,  0.3365,  1.0403,  0.0607,  0.0091,  0.3836,  2.4094],
        [-0.4387,  1.5987,  0.3238, -0.9869, -0.4428,  2.1458,  1.2981, -1.2199]])
tensor([5, 5, 4, 1, 7, 2])


In [8]:
# 1. 直接调用CrossEntropyLoss
loss = nn.CrossEntropyLoss()
print(loss(input, target))

tensor(2.0061)


In [11]:
# 2. 先调LogSoftmax，在调NLLLoss
loss1 = nn.LogSoftmax(dim=1)
loss2 = nn.NLLLoss()
y = loss1(input)
print(y)
print(loss2(y, target))

tensor([[-3.9766, -3.2576, -3.2820, -2.3950, -3.0634, -1.1845, -0.9775, -2.4635],
        [-1.3022, -1.2551, -1.7234, -2.0542, -4.1259, -3.3046, -2.6155, -4.5691],
        [-2.3398, -2.4010, -3.5093, -1.6252, -1.7531, -3.4088, -4.8590, -0.9884],
        [-1.7391, -2.2594, -1.7468, -3.0133, -3.6098, -1.1359, -4.3789, -1.9971],
        [-2.8472, -1.5717, -2.9113, -2.2075, -3.1871, -3.2387, -2.8642, -0.8384],
        [-3.4589, -1.4215, -2.6964, -4.0071, -3.4630, -0.8744, -1.7221, -4.2401]])
tensor(2.0061)
