In [4]:
import torch
import numpy as np

In [5]:
# 1. 基本张量创建
# 1.1 `torch.tensor(data)` 创建指定内容的张量，传入标量
tensor1 = torch.tensor(5)
print(tensor1)

tensor(5)


In [6]:
# 1.2 传入列表
tensor2 = torch.tensor([[1, 2, 3],[4, 5, 6]])
print(tensor2)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# 1.3 传入ndarray
tensor3 = torch.tensor(np.array([[1, 2, 3],[4, 5, 6]]))
print(tensor3)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [9]:
# 2. torch.Tensor(size)创建指定形状的张量
tensor1 = torch.Tensor(3, 2, 4)
print(tensor1.dtype)

torch.float32


In [10]:
tensor2 = torch.Tensor(3,2,3)
print(tensor2)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [12]:
tensor3 = torch.Tensor(np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]]))
print(tensor3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [13]:
# 3. 创建指定类型的张量
tensor1 = torch.IntTensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor1,tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32) torch.int32


In [14]:
tensor1 = torch.LongTensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor1,tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.int64


In [15]:
tensor1 = torch.ShortTensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor1,tensor1.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int16) torch.int16


In [17]:
tensor1 = torch.BoolTensor([[1,2,3],[4,5,6],[7,8,9]])
print(tensor1,tensor1.dtype)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]]) torch.bool


In [21]:
# 4. 指定区间的张量创建
# 4.1. `torch.arange(start, end, step)`在区间内按照步长创建张量
tensor1 = torch.arange(10,30, 2)
print(tensor1,tensor1.dtype)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28]) torch.int64


In [23]:
# 4.2. `torch.linspace(start, end, steps)`在区间内按元素数量创建张量
tensor1 = torch.linspace(10, 30, 2)
print(tensor1,tensor1.dtype)

tensor([10., 30.]) torch.float32


In [24]:
# 4.3. `torch.logspace(start, end, steps, base)`在指数区间内按指定底数创建张量
tensor1 = torch.logspace(1, 3, 3, 2)
print(tensor1,tensor1.dtype)

tensor([2., 4., 8.]) torch.float32


In [25]:
# 5. 按数值填充张量
tensor1 = torch.zeros(2, 3)
print(tensor1,tensor1.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32


In [26]:
tensor2 = torch.ones_like(tensor1)
print(tensor2,tensor2.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32


In [27]:
tensor1 = torch.full((2, 3), 6)
print(tensor1,tensor1.dtype)

tensor([[6, 6, 6],
        [6, 6, 6]]) torch.int64


In [28]:
tensor2 = torch.empty_like(tensor3)
print(tensor2,tensor2.dtype)

tensor([[1.2829e+38, 2.0515e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]]) torch.float32


In [29]:
# `torch.eye(n, [m])`创建单位矩阵
# torch.eye(n) 创建n*n的单位矩阵
tensor1 = torch.eye(3)
print(tensor1)

# torch.eye(n, m) 按指定的行和列创建
tensor2 = torch.eye(3, 4)
print(tensor2)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [31]:
# 6. 创建随机张量
# 6.1 随机分布
tensor1 = torch.rand(3, 2)
print(tensor1)

tensor([[0.5621, 0.4383],
        [0.2096, 0.4847],
        [0.6389, 0.2981]])


In [34]:
# 6.2 均匀分布，整数
tensor2 = torch.randint(1, 10, (3, 2))
print(tensor2)

tensor([[4, 7],
        [8, 4],
        [3, 4]])


In [35]:
tensor2 = torch.randint_like(tensor1, 1, 10)
print(tensor2)

tensor([[1., 6.],
        [2., 7.],
        [7., 1.]])


In [36]:
tensor1 = torch.randn(4, 2)
print(tensor1)

tensor([[ 2.6660, -1.4850],
        [ 0.1716, -0.6942],
        [-0.7462,  0.8903],
        [-1.3966, -0.5770]])


In [37]:
tensor2 = torch.normal(5, 1, tensor1.shape)
print(tensor2)

tensor([[3.7027, 7.1576],
        [5.1844, 5.0942],
        [5.3504, 4.5595],
        [4.3651, 5.6018]])


In [38]:
# torch.randperm(n) 生成从0到n-1的随机排列
tensor1 = torch.randperm(10)
print(tensor1)

tensor([4, 1, 5, 7, 6, 8, 0, 2, 9, 3])


In [39]:
# 6.6. `torch.random.initial_seed()`查看随机数种子
print(torch.random.initial_seed())

7997340527400
