In [1]:
import numpy as np
import torch

In [4]:
# 1. 张量元素类型转换
tensor1 = torch.tensor([1,2,3])
print(tensor1, tensor1.dtype)
tensor1 = tensor1.type(torch.float32)
print(tensor1, tensor1.dtype)

tensor([1, 2, 3]) torch.int64
tensor([1., 2., 3.]) torch.float32


In [5]:
tensor1 = tensor1.long()
print(tensor1,tensor1.dtype)

tensor([1, 2, 3]) torch.int64


In [6]:
tensor1 = tensor1.bool()
print(tensor1,tensor1.dtype)

tensor([True, True, True]) torch.bool


In [2]:
# Tensor与ndarray转换
import torch

# 使用numpy()方法将Tensor转换为ndarray，共享内存
tensor1 = torch.rand(3, 2)
numpy_array = tensor1.numpy()
print(tensor1)
print(numpy_array)
print(type(tensor1), type(numpy_array))
print()
tensor1[:, 0] = 4
print(tensor1)
print(numpy_array)
print()

# 使用copy()方法避免共享内存
numpy_array = tensor1.numpy().copy()
tensor1[:, 0] = -1
print(tensor1)
print(numpy_array)

tensor([[0.9413, 0.8333],
        [0.0642, 0.2486],
        [0.9351, 0.7355]])
[[0.9412732  0.8332501 ]
 [0.06419337 0.24858487]
 [0.9351286  0.7354797 ]]
<class 'torch.Tensor'> <class 'numpy.ndarray'>

tensor([[4.0000, 0.8333],
        [4.0000, 0.2486],
        [4.0000, 0.7355]])
[[4.         0.8332501 ]
 [4.         0.24858487]
 [4.         0.7354797 ]]

tensor([[-1.0000,  0.8333],
        [-1.0000,  0.2486],
        [-1.0000,  0.7355]])
[[4.         0.8332501 ]
 [4.         0.24858487]
 [4.         0.7354797 ]]


In [4]:
import torch
import numpy as np

# 使用from_numpy()方法将ndarray转换为Tensor，共享内存
numpy_array = np.random.randn(3)
tensor1 = torch.from_numpy(numpy_array)
print(numpy_array)
print(tensor1)
print()
numpy_array[0] = 100
print(numpy_array)
print(tensor1)
print()

# 使用copy()方法避免共享内存
tensor1 = torch.from_numpy(numpy_array.copy())
numpy_array[0] = -1
print(numpy_array)
print(tensor1)

[-0.27871999 -0.08086692  0.93430215]
tensor([-0.2787, -0.0809,  0.9343], dtype=torch.float64)

[ 1.00000000e+02 -8.08669224e-02  9.34302150e-01]
tensor([ 1.0000e+02, -8.0867e-02,  9.3430e-01], dtype=torch.float64)

[-1.         -0.08086692  0.93430215]
tensor([ 1.0000e+02, -8.0867e-02,  9.3430e-01], dtype=torch.float64)


In [5]:
import torch
import numpy as np

# 使用torch.tensor()将ndarray转换为Tensor
numpy_array = np.random.randn(3)
tensor1 = torch.tensor(numpy_array)
print(numpy_array)
print(tensor1)
print()
numpy_array[0] = 100
print(numpy_array)
print(tensor1)

[-0.17876486 -1.94043712 -0.79371192]
tensor([-0.1788, -1.9404, -0.7937], dtype=torch.float64)

[100.          -1.94043712  -0.79371192]
tensor([-0.1788, -1.9404, -0.7937], dtype=torch.float64)
