In [1]:
# `transpose()`交换两个维度
import torch

tensor1 = torch.randint(1, 9, (2, 3, 6))
print(tensor1)
print(tensor1.transpose(1, 2)) # 交换第1维和第2维

tensor([[[3, 6, 8, 6, 8, 3],
         [2, 3, 6, 3, 7, 6],
         [5, 5, 5, 5, 3, 5]],

        [[5, 2, 4, 4, 8, 2],
         [4, 5, 5, 8, 7, 5],
         [1, 6, 3, 7, 4, 6]]])
tensor([[[3, 2, 5],
         [6, 3, 5],
         [8, 6, 5],
         [6, 3, 5],
         [8, 7, 3],
         [3, 6, 5]],

        [[5, 4, 1],
         [2, 5, 6],
         [4, 5, 3],
         [4, 8, 7],
         [8, 7, 4],
         [2, 5, 6]]])


In [2]:
# `permute()`重新排列多个维度
import torch

tensor1 = torch.randint(1, 9, (2, 3, 6))
print(tensor1)
print(tensor1.permute(2, 0, 1)) # (2, 3, 6)->(6, 2, 3)

tensor([[[2, 6, 5, 6, 1, 3],
         [8, 3, 6, 5, 6, 5],
         [3, 6, 8, 7, 4, 3]],

        [[6, 5, 8, 2, 5, 3],
         [3, 7, 8, 5, 4, 7],
         [5, 4, 3, 5, 4, 6]]])
tensor([[[2, 8, 3],
         [6, 3, 5]],

        [[6, 3, 6],
         [5, 7, 4]],

        [[5, 6, 8],
         [8, 8, 3]],

        [[6, 5, 7],
         [2, 5, 5]],

        [[1, 6, 4],
         [5, 4, 4]],

        [[3, 5, 3],
         [3, 7, 6]]])


In [4]:
# `reshape()`调整张量的形状
import torch

tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print(tensor1.reshape(6, 10))
print(tensor1.reshape(3, -1))

tensor([[[7, 4, 4, 3],
         [7, 7, 5, 2],
         [2, 3, 1, 8],
         [2, 8, 2, 3],
         [1, 8, 8, 4]],

        [[8, 4, 7, 4],
         [3, 3, 3, 7],
         [1, 3, 4, 8],
         [3, 3, 3, 6],
         [1, 7, 3, 4]],

        [[1, 7, 7, 2],
         [3, 5, 3, 5],
         [2, 6, 5, 4],
         [3, 8, 7, 2],
         [8, 2, 8, 8]]])
tensor([[7, 4, 4, 3, 7, 7, 5, 2, 2, 3],
        [1, 8, 2, 8, 2, 3, 1, 8, 8, 4],
        [8, 4, 7, 4, 3, 3, 3, 7, 1, 3],
        [4, 8, 3, 3, 3, 6, 1, 7, 3, 4],
        [1, 7, 7, 2, 3, 5, 3, 5, 2, 6],
        [5, 4, 3, 8, 7, 2, 8, 2, 8, 8]])
tensor([[7, 4, 4, 3, 7, 7, 5, 2, 2, 3, 1, 8, 2, 8, 2, 3, 1, 8, 8, 4],
        [8, 4, 7, 4, 3, 3, 3, 7, 1, 3, 4, 8, 3, 3, 3, 6, 1, 7, 3, 4],
        [1, 7, 7, 2, 3, 5, 3, 5, 2, 6, 5, 4, 3, 8, 7, 2, 8, 2, 8, 8]])


In [7]:
# `view()`调整张量的形状，需要内存连续，共享内存
# `is_contiguous()`判断是否内存连续
# `contiguous()`转换为内存连续
import torch

tensor1 = torch.randint(1, 9, (3, 5, 4))
print(tensor1)
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续
print(tensor1.view(-1, 10))

tensor1 = tensor1.T
print(tensor1.is_contiguous()) # is_contiguous()判断是否内存连续
print(tensor1.contiguous().view(-1)) # contiguous()强制内存连续

tensor([[[7, 6, 4, 2],
         [5, 5, 1, 4],
         [6, 3, 6, 3],
         [2, 3, 2, 1],
         [6, 6, 6, 2]],

        [[7, 1, 7, 8],
         [5, 5, 6, 6],
         [2, 8, 5, 7],
         [4, 7, 8, 3],
         [5, 2, 6, 2]],

        [[8, 7, 3, 2],
         [3, 8, 1, 2],
         [1, 1, 2, 4],
         [5, 3, 7, 5],
         [6, 4, 3, 4]]])
True
tensor([[7, 6, 4, 2, 5, 5, 1, 4, 6, 3],
        [6, 3, 2, 3, 2, 1, 6, 6, 6, 2],
        [7, 1, 7, 8, 5, 5, 6, 6, 2, 8],
        [5, 7, 4, 7, 8, 3, 5, 2, 6, 2],
        [8, 7, 3, 2, 3, 8, 1, 2, 1, 1],
        [2, 4, 5, 3, 7, 5, 6, 4, 3, 4]])
False
tensor([7, 7, 8, 5, 5, 3, 6, 2, 1, 2, 4, 5, 6, 5, 6, 6, 1, 7, 5, 5, 8, 3, 8, 1,
        3, 7, 3, 6, 2, 4, 4, 7, 3, 1, 6, 1, 6, 5, 2, 2, 8, 7, 6, 6, 3, 2, 8, 2,
        4, 6, 2, 3, 7, 4, 1, 3, 5, 2, 2, 4])


In [9]:
# `unsqueeze()`在指定维度上**增加1个维度**
import torch

tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1)
# 在0维上增加一个维度
print(tensor1.unsqueeze(dim=0))
# 在1维上增加一个维度
print(tensor1.unsqueeze(dim=1))
# 在-1维上增加一个维度
print(tensor1.unsqueeze(dim=-1))

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])


In [11]:
# `squeeze()`：**删除大小为1的维度**
import torch

tensor1 = torch.tensor([1, 2, 3, 4, 5])
print(tensor1.unsqueeze_(dim=0))
print(tensor1.squeeze())

tensor([[1, 2, 3, 4, 5]])
tensor([1, 2, 3, 4, 5])


In [14]:
# 张量拼接操作
# `torch.cat()`张量拼接，按已有维度拼接。除拼接维度外，其他维度大小须相同
import torch

tensor1 = torch.randint(1, 9, (2, 2, 5))
tensor2 = torch.randint(1, 9, (2, 1, 5))
print(tensor1)
print(tensor2)
print(torch.cat([tensor1, tensor2], dim=1))

tensor([[[7, 7, 8, 3, 2],
         [3, 3, 3, 5, 4]],

        [[6, 6, 8, 7, 1],
         [7, 8, 8, 6, 2]]])
tensor([[[6, 2, 5, 5, 4]],

        [[3, 8, 6, 1, 7]]])
tensor([[[7, 7, 8, 3, 2],
         [3, 3, 3, 5, 4],
         [6, 2, 5, 5, 4]],

        [[6, 6, 8, 7, 1],
         [7, 8, 8, 6, 2],
         [3, 8, 6, 1, 7]]])


In [15]:
# `torch.stack()`张量堆叠，按新维度堆叠。所有张量形状必须一致
import torch

torch.manual_seed(42)
tensor1 = torch.randint(1, 9, (3, 1, 5))
tensor2 = torch.randint(1, 9, (3, 1, 5))
print(tensor1)
print(tensor2)
tensor3 = torch.stack([tensor1, tensor2], dim=2)
print(tensor3)
print(tensor3.shape)

tensor([[[7, 4, 5, 7, 3]],

        [[8, 5, 5, 7, 2]],

        [[3, 7, 3, 3, 8]]])
tensor([[[5, 4, 8, 8, 3]],

        [[6, 5, 2, 8, 4]],

        [[6, 6, 2, 8, 4]]])
tensor([[[[7, 4, 5, 7, 3],
          [5, 4, 8, 8, 3]]],


        [[[8, 5, 5, 7, 2],
          [6, 5, 2, 8, 4]]],


        [[[3, 7, 3, 3, 8],
          [6, 6, 2, 8, 4]]]])
torch.Size([3, 1, 2, 5])
