In [2]:
import torch
import torch.nn as nn
# 创建一个全连接层
linear = nn.Linear(5,3)
print(linear.weight)

Parameter containing:
tensor([[ 0.0914,  0.2417, -0.1142, -0.0004, -0.3265],
        [ 0.0973, -0.1210,  0.2305,  0.2138,  0.0348],
        [-0.2817,  0.0065, -0.3097,  0.1948, -0.3165]], requires_grad=True)


In [3]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
nn.init.ones_(linear.weight)
print(linear.weight)
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([10., 10., 10.], requires_grad=True)


In [6]:
# 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], requires_grad=True)


In [11]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, 1, 10)
print(linear.weight)

Parameter containing:
tensor([[9.2152, 8.2894, 5.3197, 8.7454, 3.6395],
        [1.4197, 4.0281, 3.6460, 1.4326, 6.4573],
        [1.3677, 3.6102, 2.9054, 6.4002, 5.5193]], requires_grad=True)


In [12]:
# 正态分布初始化
nn.init.normal_(linear.weight, 0, 1)
print(linear.weight)

Parameter containing:
tensor([[-1.5801, -0.6634, -0.5728,  1.5011,  0.4294],
        [-1.4468, -0.0467, -0.3715, -1.1257, -0.5756],
        [ 0.1946, -0.4704,  2.1439,  1.0589,  1.1565]], requires_grad=True)
