In [1]:
import torch

In [3]:
x1 = torch.tensor([1.,2.,3.,4.],requires_grad=True)
x2 = torch.tensor([1.,2.,3.,4.],requires_grad=True)
print(x1)
print(x2)

tensor([1., 2., 3., 4.], requires_grad=True)
tensor([1., 2., 3., 4.], requires_grad=True)


In [7]:
y1 = x1.sigmoid()
y2 = x2.sigmoid()
print(y1)
print(y2)

tensor([0.7311, 0.8808, 0.9526, 0.9820], grad_fn=<SigmoidBackward0>)
tensor([0.7311, 0.8808, 0.9526, 0.9820], grad_fn=<SigmoidBackward0>)


In [8]:
# 反向传播计算梯度
y1.sum().backward()
y2.sum().backward()
print("x1.grad = ",x1.grad)
print("x2.grad = ",x2.grad)

x1.grad =  tensor([0.3932, 0.2100, 0.0904, 0.0353])
x2.grad =  tensor([0.3932, 0.2100, 0.0904, 0.0353])


In [11]:
z1 = y1.data
z2 = y2.detach()
print(z1)
print(z2)
print(z1.requires_grad)
print(z2.requires_grad)
print(y1.requires_grad)
print(y2.requires_grad)

tensor([0.7311, 0.8808, 0.9526, 0.9820])
tensor([0.7311, 0.8808, 0.9526, 0.9820])
False
False
True
True


In [12]:
z1.zero_()
z2.zero_()
print(y1)
print(y2)

tensor([0., 0., 0., 0.], grad_fn=<SigmoidBackward0>)
tensor([0., 0., 0., 0.], grad_fn=<SigmoidBackward0>)


In [13]:
y2.sum().backward()
print(x2.grad)

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.